routes/web.php
<?php

use App\Http\Controllers\DashboardController;
use App\Http\Controllers\HomeController;
use App\Http\Controllers\petugas\BukuPetugasController;
use App\Http\Controllers\Petugas\DashboardPetugasController;
use App\Http\Controllers\Petugas\DendaPetugasController;
use App\Http\Controllers\petugas\KelasPetugasController;
use App\Http\Controllers\petugas\LaporanPetugasController;
use App\Http\Controllers\petugas\PeminjamanPetugasController;
use App\Http\Controllers\petugas\PengambalianPetugasController;
use App\Http\Controllers\Petugas\PetugasController;
use App\Http\Controllers\petugas\ProfilPetugasController;
use App\Http\Controllers\petugas\RakPetugasController;
use App\Http\Controllers\Petugas\SiswaPetugasController;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

// Route::get('/', function () {
//     return view('welcome');
// });

Route::get('/', [DashboardController::class, 'index'])->name('home.index');
Route::get('/buku', [DashboardController::class, 'buku'])->name('home.buku');
Route::get('/buku/cari', [DashboardController::class, 'cari'])->name('home.cari');

Auth::routes();

Route::get('/home', [HomeController::class, 'index'])->name('home');

Route::middleware(['auth', 'user-access:Petugas'])->group(function () {
    Route::get('/petugas/dashboard', [DashboardPetugasController::class, 'index'])->name('petugas.dashboard');

    Route::resource('/petugas/siswa', SiswaPetugasController::class);

    Route::resource('/petugas/kelas', KelasPetugasController::class);

    Route::resource('/petugas/rak', RakPetugasController::class);

    Route::resource('/petugas/buku', BukuPetugasController::class);

    Route::resource('/petugas/petugas', PetugasController::class);

    Route::get('/petugas/peminjaman', [PeminjamanPetugasController::class, 'index'])->name('peminjaman.index');
    Route::get('/petugas/peminjaman/scan', [PeminjamanPetugasController::class, 'cek'])->name('peminjaman.scan');
    Route::post('/petugas/peminjaman/pinjam', [PeminjamanPetugasController::class, 'pinjam'])->name('peminjaman.store');

    Route::get('/petugas/pengembalian', [PengambalianPetugasController::class, 'index'])->name('pengembalian.index');
    Route::get('/petugas/pengembalian/scan', [PengambalianPetugasController::class, 'scan'])->name('pengembalian.scan');
    Route::post('/petugas/pengembalian/proses', [PengambalianPetugasController::class, 'proses'])->name('pengembalian.proses');

    Route::get('/petugas/profile', [ProfilPetugasController::class, 'index'])->name('profile.index');
    Route::put('/petugas/profile/edit-profile/{profile}', [ProfilPetugasController::class, 'data'])->name('profile.profile');
    Route::put('/petugas/profile/edit-password/{profile}', [ProfilPetugasController::class, 'password'])->name('profile.password');

    Route::get('/petugas/profile/foto', [ProfilPetugasController::class, 'foto'])->name('profile.foto');
    Route::put('/petugas/profile/foto-update/{profile}', [ProfilPetugasController::class, 'foto_update'])->name('profile.foto_update');

    Route::get('/petugas/laporan', [LaporanPetugasController::class, 'index'])->name('laporan.index');
    Route::get('/petugas/laporan/cetak', [LaporanPetugasController::class, 'cetak_pdf'])->name('laporan.cetak_pdf');
    Route::post('/petugas/laporan/cari', [LaporanPetugasController::class, 'cari_laporan'])->name('laporan.cari_laporan');

    Route::resource('/petugas/denda', DendaPetugasController::class);

});

app/Models/Buku.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Buku extends Model
{
    use HasFactory;

    protected $table='buku';
    protected $primaryKey='id_buku';
    protected $fillable = [
        'kode_buku',
        'nama_buku',
        'penerbit',
        'rak',
        'stok_buku',
        'foto_buku',
    ];

}

app/Http/Controllers/Petugas/BukuPetugasController.php
<?php

namespace App\Http\Controllers\petugas;

use App\Http\Controllers\Controller;
use App\Models\Buku;
use App\Models\Rak;
use Illuminate\Http\Request;

class BukuPetugasController extends Controller
{
    public function index()
    {
        $buku = Buku::join('rak', 'rak.id_rak', '=', 'buku.rak')
            ->select('buku.*', 'rak.jenis_rak')
            ->orderBy('buku.nama_buku', 'ASC')
            ->get();

        return Response(view('petugas.buku.buku', compact(['buku'])));
    }

    public function create()
    {
        $rak = Rak::orderBy('jenis_rak', 'ASC')->get();
        return view('petugas.buku.buku_store', compact(['rak']));
    }

    public function store(Request $request)
    {
        $request->validate([
            'kode_buku' => 'required|unique:buku,kode_buku',
            'judul_buku' => 'required|unique:buku,nama_buku',
            'penerbit' => 'required',
            'rak' => 'required',
            'stok' => 'required',
            'foto' => 'required'
        ]);

        if ($request->hasFile('foto')) {
            $foto_profile = $request->file('foto')->getClientOriginalName();
            $request->foto->move(public_path('foto_buku'), $foto_profile);
        }

        Buku::create([
            'kode_buku' => $request->kode_buku,
            'nama_buku' => $request->judul_buku,
            'penerbit' => $request->penerbit,
            'rak' => $request->rak,
            'stok_buku' => $request->stok,
            'foto_buku' => $foto_profile,
        ]);

        return to_route('buku.index')->with('success', 'Berhasil Menambahkan Buku Baru');
    }

    public function show($id)
    {
        //
    }

    public function edit($id)
    {
        $buku = Buku::find($id);
        $rak = Rak::orderBy('jenis_rak', 'ASC')->get();

        return view('petugas.buku.buku_edit', compact(['buku', 'rak']));
    }

    public function update(Request $request, $id)
    {
        $request->validate([
            'kode_buku' => 'required',
            'judul_buku' => 'required',
            'penerbit' => 'required',
            'rak' => 'required',
            'stok' => 'required',
        ]);

        if ($request->foto == NULL) {
            Buku::find($id)->update([
                'kode_buku' => $request->kode_buku,
                'nama_buku' => $request->judul_buku,
                'penerbit' => $request->penerbit,
                'rak' => $request->rak,
                'stok_buku' => $request->stok,
            ]);

            return to_route('buku.index')->with('success', 'Berhasil Memperbaharui Data Buku');
        }

        if ($request->hasFile('foto')) {
            $foto_profile = $request->file('foto')->getClientOriginalName();
            $request->foto->move(public_path('foto_buku'), $foto_profile);
        }

        Buku::find($id)->update([
            'kode_buku' => $request->kode_buku,
            'nama_buku' => $request->judul_buku,
            'penerbit' => $request->penerbit,
            'rak' => $request->rak,
            'stok_buku' => $request->stok,
            'foto_buku' => $foto_profile,
        ]);

        return to_route('buku.index')->with('success', 'Berhasil Memperbaharui Data Buku');
    }

    public function destroy($id)
    {
        Buku::find($id)->delete();

        return back()->with('success', 'Berhasil Menghapus Buku');
    }
}

app/Http/Controllers/Petugas/DashboardPetugasController.php
<?php

namespace App\Http\Controllers\Petugas;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\DB;

class DashboardPetugasController extends Controller
{
    public function index()
    {
        $siswa = DB::table('siswa')->get();
        $buku = DB::table('buku')->get();
        $pinjam = DB::table('riwayat_pinjam')->where('status', 'pinjam')->get();
        $kembali = DB::table('riwayat_pinjam')->where('status', 'selesai')->get();
        $aktivity = DB::table('riwayat_pinjam')
            ->join('siswa', 'siswa.id_siswa', '=', 'riwayat_pinjam.id_siswa')
            ->join('buku', 'buku.id_buku', '=', 'riwayat_pinjam.id_buku')
            ->select('riwayat_pinjam.*', 'siswa.nama_siswa', 'siswa.foto', 'buku.nama_buku')
            ->latest()
            ->limit(5)
            ->get();

        return view('petugas.dashboard.dashboard', compact('siswa', 'buku', 'pinjam', 'kembali', 'aktivity'));
    }
}

app/Http/Controllers/Petugas/DendaPetugasController.php
<?php

namespace App\Http\Controllers\Petugas;

use App\Http\Controllers\Controller;
use App\Models\Denda;
use Illuminate\Http\Request;

class DendaPetugasController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $denda = Denda::get();
        return view('petugas.denda.denda', compact(['denda']));
    }

    public function store(Request $request)
    {
        Denda::create([
            'nominal_denda' => $request->nominal_denda,
        ]);

        return back()->with('success', 'Berhasil Menambahkan Denda Peminjaman');
    }
    public function update(Request $request, $id)
    {
        Denda::find($id)->update([
            'nominal_denda' => $request->nominal_denda,
        ]);

        return back()->with('success', 'Berhasil Memperbaharui Denda Peminjaman');
    }

    public function destroy($id)
    {
        Denda::find($id)->delete();

        return back()->with('success', 'Berhasil Menghapus Denda Peminjaman');
    }
}

app/Http/Controllers/Petugas/KelasPetugasController.php
<?php

namespace App\Http\Controllers\petugas;

use App\Http\Controllers\Controller;
use App\Models\Kelas;
use Illuminate\Support\Facades\Validator;
use Illuminate\Http\Request;

class KelasPetugasController extends Controller
{
   
    public function index()
    {
        $kelas = Kelas::orderBy('jenis_kelas', 'ASC')->paginate(8);
        return view('petugas.kelas.kelas', compact(['kelas']));
    }


    public function store(Request $request)
    {
        $validator = Validator::make($request->all(), [
            'jenis_kelas'=> 'unique:kelas,jenis_kelas'
        ]);

        if ($validator->fails()) {
            return back()->with('fail', 'Kelas Telah Ada Mohon Cek Ulang');
        }

        Kelas::create([
            'jenis_kelas'=>$request->jenis_kelas,
        ]);

        return back()->with('success', 'Berhasil Menambahkan Kelas Baru');
    }


    public function update(Request $request, $id)
    {
        Kelas::find($id)->update([
            'jenis_kelas'=>$request->jenis_kelas
        ]);

        return back()->with('success', 'Berhasil Perbaharui Kelas');
    }

    
    public function destroy($id)
    {
        Kelas::find($id)->delete();

        return back()->with('success', 'Berhasil Menghapus Kelas');
    }
}

app/Http/Controllers/Petugas/LaporanPetugasController.php
<?php

namespace App\Http\Controllers\petugas;

use App\Http\Controllers\Controller;
use App\Models\Riwayat;
use Illuminate\Http\Request;

use PDF;

class LaporanPetugasController extends Controller
{
    public function index()
    {
        $riwayat = Riwayat::join('siswa', 'siswa.id_siswa', '=', 'riwayat_pinjam.id_siswa')
            ->join('kelas', 'kelas.id_kelas', '=', 'siswa.kelas')
            ->join('buku', 'buku.id_buku', '=', 'riwayat_pinjam.id_buku')
            ->select('riwayat_pinjam.*', 'buku.nama_buku', 'buku.kode_buku', 'buku.foto_buku', 'siswa.nis', 'siswa.nama_siswa', 'kelas.jenis_kelas')
            ->latest()
            ->get();

        return view('petugas.laporan.laporan', compact(['riwayat']));
    }

    public function cetak_pdf()
    {
        $riwayat = Riwayat::join('siswa', 'siswa.id_siswa', '=', 'riwayat_pinjam.id_siswa')
            ->join('kelas', 'kelas.id_kelas', '=', 'siswa.kelas')
            ->join('buku', 'buku.id_buku', '=', 'riwayat_pinjam.id_buku')
            ->select('riwayat_pinjam.*', 'buku.nama_buku', 'buku.kode_buku', 'buku.foto_buku', 'siswa.nis', 'siswa.nama_siswa', 'kelas.jenis_kelas')
            ->latest()
            ->get();

        $pdf = PDF::loadview('petugas.laporan.print_laporan_all', ['riwayat' => $riwayat]);

        return $pdf->stream();
    }

    public function cari_laporan(Request $request)
    {
        $data = explode(' - ', $request->daterange);

        $startDate = date('Y-m-d', strtotime($data[0]));
        $endDate = date('Y-m-d', strtotime($data[1]));

        $riwayat = Riwayat::join('siswa', 'siswa.id_siswa', '=', 'riwayat_pinjam.id_siswa')
            ->join('kelas', 'kelas.id_kelas', '=', 'siswa.kelas')
            ->join('buku', 'buku.id_buku', '=', 'riwayat_pinjam.id_buku')
            ->select('riwayat_pinjam.*', 'buku.nama_buku', 'buku.kode_buku', 'buku.foto_buku', 'siswa.nis', 'siswa.nama_siswa', 'kelas.jenis_kelas')
            ->whereBetween('riwayat_pinjam.tanggal_kembali', [$startDate, $endDate])
            ->get();

        $pdf = PDF::loadview('petugas.laporan.print_laporan_all', ['riwayat' => $riwayat]);
        return $pdf->stream();
    }
}

app/Http/Controllers/Petugas/PeminjamanPetugasController.php
<?php

namespace App\Http\Controllers\petugas;

use App\Http\Controllers\Controller;
use App\Models\Buku;
use App\Models\Pinjam;
use App\Models\Riwayat;
use App\Models\Siswa;
use Illuminate\Http\Request;

class PeminjamanPetugasController extends Controller
{
    public function index()
    {
        return view('petugas.peminjaman.peminjaman');
    }

    public function cek(Request $request)
    {
        $request->validate([
            'barcode'=>'required'
        ]);

        $barcode = $request->barcode;

        $buku = Buku::where('stok_buku','>',0)->orderBy('nama_buku', 'ASC')->get();

        $siswa = Siswa::join('kelas','kelas.id_kelas','=','siswa.kelas')
        ->select('siswa.*', 'kelas.jenis_kelas')
        ->where('siswa.barcode', $barcode)
        ->get();

        if($siswa->count() < 1)
        {
            return back()->with('fail','Mohon Maaf Data Siswa Tidak Di Temukan');
        }


        return view('petugas.peminjaman.peminjaman_cek', compact(['siswa','buku']));
    }


    public function pinjam(Request $request)
    {
        $siswa = Pinjam::where('id_siswa',$request->siswa)->get();
        $count =$siswa->count();

        if ($count > 0) {
            return back()->with('fail','Maaf Siswa Masih Memiliki Pinjaman Buku');
        }

        $request->validate([
            'buku1'=>'required'
        ]);

        $id_buku1 = $request->buku1;

        $tanggal = date('Y-m-d', strtotime("+7 day", strtotime(date("Y-m-d"))));

        Pinjam::create([
            'id_siswa'=>$request->siswa,
            'id_buku'=>$request->buku1,
            'tanggal_kembali'=>$tanggal

        ]);

        Buku::find($id_buku1)->decrement('stok_buku');

        Riwayat::create([
            'id_siswa'=>$request->siswa,
            'id_buku'=>$request->buku1,
            'tanggal_kembali'=>$tanggal,
            'status'=>'pinjam'
        ]);

        if (!empty($request->buku2)) {
            Pinjam::create([
                'id_siswa'=>$request->siswa,
                'id_buku'=>$request->buku2,
                'tanggal_kembali'=>$tanggal
            ]);

            $id_buku2 = $request->buku2;

            Buku::find($id_buku2)->decrement('stok_buku');

            Riwayat::create([
                'id_siswa'=>$request->siswa,
                'id_buku'=>$request->buku2,
                'tanggal_kembali'=>$tanggal,
                'status'=>'pinjam'
            ]);
        }
        if (!empty($request->buku3)) {
            Pinjam::create([
                'id_siswa'=>$request->siswa,
                'id_buku'=>$request->buku3,
                'tanggal_kembali'=>$tanggal
            ]);

            $id_buku3 = $request->buku3;

            Buku::find($id_buku3)->decrement('stok_buku');

            Riwayat::create([
                'id_siswa'=>$request->siswa,
                'id_buku'=>$request->buku3,
                'tanggal_kembali'=>$tanggal,
                'status'=>'pinjam'
            ]);
        }

        return to_route('peminjaman.index')->with('success', 'Berhasil Melakukan Peminjaman Buku');
    }
}

app/Http/Controllers/Petugas/RakPetugasController.php
<?php

namespace App\Http\Controllers\petugas;

use App\Http\Controllers\Controller;
use App\Models\Rak;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Validator;

class RakPetugasController extends Controller
{
    public function index()
    {
        $rak = Rak::orderBy('jenis_rak','ASC')->paginate(8);
        return view('petugas.rak.rak', compact(['rak']));
    }

    public function store(Request $request)
    {
        $validator = Validator::make($request->all(), [
            'jenis_rak'=> 'unique:rak,jenis_rak'
        ]);

        if ($validator->fails()) {
            return back()->with('fail', 'Rak Buku Telah Ada Mohon Cek Ulang');
        }

        rak::create([
            'jenis_rak'=>$request->jenis_rak,
        ]);

        return back()->with('success', 'Berhasil Menambahkan Rak Buku Baru');
    }


  
    public function update(Request $request, $id)
    {
        Rak::find($id)->update([
            'jenis_rak'=>$request->jenis_rak
        ]);

        return back()->with('success', 'Berhasil Perbaharui Rak Buku');
    }

    public function destroy($id)
    {
        Rak::find($id)->delete();

        return back()->with('success', 'Berhasil Menghapus Rak Buku');
    }
}

resources/views/petugas/buku/buku.blade.php
@extends('petugas.theme.master')

@section('content')
    <div class="container-fluid px-xxl-65 px-xl-20 mt-20">
        <div class="hk-pg-header">
            <h4 class="hk-pg-title"><span class="pg-title-icon"><i class="fa fa-book"></i></span>Buku</h4>
        </div>

        @if (session('success'))
            <div class="alert alert-success alert-wth-icon fade show" role="alert">
                <span class="alert-icon-wrap"><i class="zmdi zmdi-check-circle"></i></span>
                {{ session('success') }}
            </div>
        @elseif (session('fail'))
            <div class="alert alert-danger alert-wth-icon fade show" role="alert">
                <span class="alert-icon-wrap"><i class="zmdi zmdi-block"></i></span>
                {{ session('fail') }}
            </div>
        @endif

        <div class="row">
            <div class="col-xl-12">
                <a href="{{ route('buku.create') }}" class="btn btn-success btn-wth-icon btn-sm mb-20">
                    <span class="icon-label">
                        <span class="material-icons">
                            create_new_folder
                        </span>
                    </span>
                    <span class="btn-text">Tambah Buku Baru</span>
                </a>
                <section class="hk-sec-wrapper">
                    <h5 class="hk-sec-title">Data Buku</h5>
                    <p class="mb-20">Data Buku Yang Terdaftar Di  Perpustakaan dan Dapat Di Pinjam </p>
                    <div class="row">
                        <div class="col-sm">
                            <div class="table-wrap">
                                <table id="datable_1" class="table table-hover w-100 display pb-30">
                                    <thead>
                                        <tr>
                                            <th>Kode Buku</th>
                                            <th>Judul Buku</th>
                                            <th>Penerbit</th>
                                            <th>Rak Buku</th>
                                            <th>Stok Buku</th>
                                            <th>Foto Buku</th>
                                            <th class="text-center">Action</th>
                                        </tr>
                                    </thead>
                                    <tbody>
                                        @foreach ($buku as $data)
                                            <tr>
                                                <td>{!! DNS1D::getBarcodeHTML($data->kode_buku, 'C39') !!}</td>
                                                <td>{{ Str::title($data->nama_buku) }}</td>
                                                <td>{{ Str::upper($data->penerbit) }}</td>
                                                <td>{{ Str::title($data->jenis_rak) }}</td>
                                                <td>
                                                    @if ($data->stok_buku < 1)
                                                    <span class="badge badge-danger">Stok Buku Habis</span>
                                                    @else
                                                    <span class="badge badge-success">Sisa Stok : {{ $data->stok_buku }}</span>
                                                    @endif
                                                </td>
                                                <td class="text-center">
                                                    <img src="/foto_buku/{{ $data->foto_buku }}" height="60"
                                                            width="60" alt="">
                                                </td>
                                                <td class="text-center">
                                                    <a href="{{ route('buku.edit', $data->id_buku) }}"
                                                        class="btn btn-icon btn-icon-circle btn-blue btn-icon-style-3"
                                                        data-toggle="tooltip" data-placement="top" title="Edit">
                                                        <span class="btn-icon-wrap">
                                                            <span class="material-icons">
                                                                edit
                                                            </span>
                                                        </span>
                                                    </a>
                                                    <a href="{{ route('buku.destroy', $data->id_buku) }}"
                                                        class="btn btn-icon btn-icon-circle btn-blue btn-icon-style-3"
                                                        data-toggle="tooltip" data-placement="top" title="Hapus"
                                                        onclick="event.preventDefault();
                                                        document.getElementById('buku-delete-form-{{ $data->id_buku }}').submit();">
                                                        <span class="btn-icon-wrap">
                                                            <span class="material-icons">
                                                                delete
                                                            </span>
                                                        </span>
                                                    </a>
                                                    <form id="buku-delete-form-{{ $data->id_buku }}"
                                                        action="{{ route('buku.destroy', $data->id_buku) }}"
                                                        method="POST" class="d-none">
                                                        @csrf
                                                        @method('delete')
                                                    </form>
                                                </td>
                                            </tr>
                                        @endforeach
                                    </tbody>
                                </table>
                            </div>
                        </div>
                    </div>
                </section>
            </div>
        </div>
    </div>
@endsection

@section('css')
    <!-- Data Table CSS -->
    <link href="/theme/vendors/datatables.net-dt/css/jquery.dataTables.min.css" rel="stylesheet" type="text/css" />
    <link href="/theme/vendors/datatables.net-responsive-dt/css/responsive.dataTables.min.css" rel="stylesheet" type="text/css" />
@endsection

@section('js')
    <script>
        window.setTimeout(function() {
            $(".alert").fadeTo(700, 0).slideUp(500, function() {
                $(this).remove();
            });
        }, 2500);
    </script>
    <!-- Data Table JavaScript -->
    <script src="/theme/vendors/datatables.net/js/jquery.dataTables.min.js"></script>
    <script src="/theme/vendors/datatables.net-bs4/js/dataTables.bootstrap4.min.js"></script>
    <script src="/theme/vendors/datatables.net-dt/js/dataTables.dataTables.min.js"></script>
    <script src="/theme/vendors/datatables.net-buttons/js/dataTables.buttons.min.js"></script>
    <script src="/theme/vendors/datatables.net-buttons-bs4/js/buttons.bootstrap4.min.js"></script>
    <script src="/theme/vendors/datatables.net-buttons/js/buttons.flash.min.js"></script>
    <script src="/theme/vendors/jszip/dist/jszip.min.js"></script>
    <script src="/theme/vendors/pdfmake/build/pdfmake.min.js"></script>
    <script src="/theme/vendors/pdfmake/build/vfs_fonts.js"></script>
    <script src="/theme/vendors/datatables.net-buttons/js/buttons.html5.min.js"></script>
    <script src="/theme/vendors/datatables.net-buttons/js/buttons.print.min.js"></script>
    <script src="/theme/vendors/datatables.net-responsive/js/dataTables.responsive.min.js"></script>
    <script src="/theme/dist/js/dataTables-data.js"></script>
@endsection