routes/web.php
<?php

use App\Http\Controllers\DashboardController;
use App\Http\Controllers\HomeController;
use App\Http\Controllers\petugas\BukuPetugasController;
use App\Http\Controllers\Petugas\DashboardPetugasController;
use App\Http\Controllers\Petugas\DendaPetugasController;
use App\Http\Controllers\petugas\KelasPetugasController;
use App\Http\Controllers\petugas\LaporanPetugasController;
use App\Http\Controllers\petugas\PeminjamanPetugasController;
use App\Http\Controllers\petugas\PengambalianPetugasController;
use App\Http\Controllers\Petugas\PetugasController;
use App\Http\Controllers\petugas\ProfilPetugasController;
use App\Http\Controllers\petugas\RakPetugasController;
use App\Http\Controllers\Petugas\SiswaPetugasController;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

// Route::get('/', function () {
//     return view('welcome');
// });

Route::get('/', [DashboardController::class, 'index'])->name('home.index');
Route::get('/buku', [DashboardController::class, 'buku'])->name('home.buku');
Route::get('/buku/cari', [DashboardController::class, 'cari'])->name('home.cari');

Auth::routes();

Route::get('/home', [HomeController::class, 'index'])->name('home');

Route::middleware(['auth', 'user-access:Petugas'])->group(function () {
    Route::get('/petugas/dashboard', [DashboardPetugasController::class, 'index'])->name('petugas.dashboard');

    Route::resource('/petugas/siswa', SiswaPetugasController::class);

    Route::resource('/petugas/kelas', KelasPetugasController::class);

    Route::resource('/petugas/rak', RakPetugasController::class);

    Route::resource('/petugas/buku', BukuPetugasController::class);

    Route::resource('/petugas/petugas', PetugasController::class);

    Route::get('/petugas/peminjaman', [PeminjamanPetugasController::class, 'index'])->name('peminjaman.index');
    Route::get('/petugas/peminjaman/scan', [PeminjamanPetugasController::class, 'cek'])->name('peminjaman.scan');
    Route::post('/petugas/peminjaman/pinjam', [PeminjamanPetugasController::class, 'pinjam'])->name('peminjaman.store');

    Route::get('/petugas/pengembalian', [PengambalianPetugasController::class, 'index'])->name('pengembalian.index');
    Route::get('/petugas/pengembalian/scan', [PengambalianPetugasController::class, 'scan'])->name('pengembalian.scan');
    Route::post('/petugas/pengembalian/proses', [PengambalianPetugasController::class, 'proses'])->name('pengembalian.proses');

    Route::get('/petugas/profile', [ProfilPetugasController::class, 'index'])->name('profile.index');
    Route::put('/petugas/profile/edit-profile/{profile}', [ProfilPetugasController::class, 'data'])->name('profile.profile');
    Route::put('/petugas/profile/edit-password/{profile}', [ProfilPetugasController::class, 'password'])->name('profile.password');

    Route::get('/petugas/profile/foto', [ProfilPetugasController::class, 'foto'])->name('profile.foto');
    Route::put('/petugas/profile/foto-update/{profile}', [ProfilPetugasController::class, 'foto_update'])->name('profile.foto_update');

    Route::get('/petugas/laporan', [LaporanPetugasController::class, 'index'])->name('laporan.index');
    Route::get('/petugas/laporan/cetak', [LaporanPetugasController::class, 'cetak_pdf'])->name('laporan.cetak_pdf');
    Route::post('/petugas/laporan/cari', [LaporanPetugasController::class, 'cari_laporan'])->name('laporan.cari_laporan');

    Route::resource('/petugas/denda', DendaPetugasController::class);

});

app/Http/Controllers/Petugas/BukuPetugasController.php
<?php

namespace App\Http\Controllers\petugas;

use App\Http\Controllers\Controller;
use App\Models\Buku;
use App\Models\Rak;
use Illuminate\Http\Request;

class BukuPetugasController extends Controller
{
    public function index()
    {
        $buku = Buku::join('rak', 'rak.id_rak', '=', 'buku.rak')
            ->select('buku.*', 'rak.jenis_rak')
            ->orderBy('buku.nama_buku', 'ASC')
            ->get();

        return Response(view('petugas.buku.buku', compact(['buku'])));
    }

    public function create()
    {
        $rak = Rak::orderBy('jenis_rak', 'ASC')->get();
        return view('petugas.buku.buku_store', compact(['rak']));
    }

    public function store(Request $request)
    {
        $request->validate([
            'kode_buku' => 'required|unique:buku,kode_buku',
            'judul_buku' => 'required|unique:buku,nama_buku',
            'penerbit' => 'required',
            'rak' => 'required',
            'stok' => 'required',
            'foto' => 'required'
        ]);

        if ($request->hasFile('foto')) {
            $foto_profile = $request->file('foto')->getClientOriginalName();
            $request->foto->move(public_path('foto_buku'), $foto_profile);
        }

        Buku::create([
            'kode_buku' => $request->kode_buku,
            'nama_buku' => $request->judul_buku,
            'penerbit' => $request->penerbit,
            'rak' => $request->rak,
            'stok_buku' => $request->stok,
            'foto_buku' => $foto_profile,
        ]);

        return to_route('buku.index')->with('success', 'Berhasil Menambahkan Buku Baru');
    }

    public function show($id)
    {
        //
    }

    public function edit($id)
    {
        $buku = Buku::find($id);
        $rak = Rak::orderBy('jenis_rak', 'ASC')->get();

        return view('petugas.buku.buku_edit', compact(['buku', 'rak']));
    }

    public function update(Request $request, $id)
    {
        $request->validate([
            'kode_buku' => 'required',
            'judul_buku' => 'required',
            'penerbit' => 'required',
            'rak' => 'required',
            'stok' => 'required',
        ]);

        if ($request->foto == NULL) {
            Buku::find($id)->update([
                'kode_buku' => $request->kode_buku,
                'nama_buku' => $request->judul_buku,
                'penerbit' => $request->penerbit,
                'rak' => $request->rak,
                'stok_buku' => $request->stok,
            ]);

            return to_route('buku.index')->with('success', 'Berhasil Memperbaharui Data Buku');
        }

        if ($request->hasFile('foto')) {
            $foto_profile = $request->file('foto')->getClientOriginalName();
            $request->foto->move(public_path('foto_buku'), $foto_profile);
        }

        Buku::find($id)->update([
            'kode_buku' => $request->kode_buku,
            'nama_buku' => $request->judul_buku,
            'penerbit' => $request->penerbit,
            'rak' => $request->rak,
            'stok_buku' => $request->stok,
            'foto_buku' => $foto_profile,
        ]);

        return to_route('buku.index')->with('success', 'Berhasil Memperbaharui Data Buku');
    }

    public function destroy($id)
    {
        Buku::find($id)->delete();

        return back()->with('success', 'Berhasil Menghapus Buku');
    }
}

app/Http/Controllers/Petugas/DashboardPetugasController.php
<?php

namespace App\Http\Controllers\Petugas;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\DB;

class DashboardPetugasController extends Controller
{
    public function index()
    {
        $siswa = DB::table('siswa')->get();
        $buku = DB::table('buku')->get();
        $pinjam = DB::table('riwayat_pinjam')->where('status', 'pinjam')->get();
        $kembali = DB::table('riwayat_pinjam')->where('status', 'selesai')->get();
        $aktivity = DB::table('riwayat_pinjam')
            ->join('siswa', 'siswa.id_siswa', '=', 'riwayat_pinjam.id_siswa')
            ->join('buku', 'buku.id_buku', '=', 'riwayat_pinjam.id_buku')
            ->select('riwayat_pinjam.*', 'siswa.nama_siswa', 'siswa.foto', 'buku.nama_buku')
            ->latest()
            ->limit(5)
            ->get();

        return view('petugas.dashboard.dashboard', compact('siswa', 'buku', 'pinjam', 'kembali', 'aktivity'));
    }
}

app/Http/Controllers/Petugas/DendaPetugasController.php
<?php

namespace App\Http\Controllers\Petugas;

use App\Http\Controllers\Controller;
use App\Models\Denda;
use Illuminate\Http\Request;

class DendaPetugasController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $denda = Denda::get();
        return view('petugas.denda.denda', compact(['denda']));
    }

    public function store(Request $request)
    {
        Denda::create([
            'nominal_denda' => $request->nominal_denda,
        ]);

        return back()->with('success', 'Berhasil Menambahkan Denda Peminjaman');
    }
    public function update(Request $request, $id)
    {
        Denda::find($id)->update([
            'nominal_denda' => $request->nominal_denda,
        ]);

        return back()->with('success', 'Berhasil Memperbaharui Denda Peminjaman');
    }

    public function destroy($id)
    {
        Denda::find($id)->delete();

        return back()->with('success', 'Berhasil Menghapus Denda Peminjaman');
    }
}

app/Http/Controllers/Petugas/KelasPetugasController.php
<?php

namespace App\Http\Controllers\petugas;

use App\Http\Controllers\Controller;
use App\Models\Kelas;
use Illuminate\Support\Facades\Validator;
use Illuminate\Http\Request;

class KelasPetugasController extends Controller
{
   
    public function index()
    {
        $kelas = Kelas::orderBy('jenis_kelas', 'ASC')->paginate(8);
        return view('petugas.kelas.kelas', compact(['kelas']));
    }


    public function store(Request $request)
    {
        $validator = Validator::make($request->all(), [
            'jenis_kelas'=> 'unique:kelas,jenis_kelas'
        ]);

        if ($validator->fails()) {
            return back()->with('fail', 'Kelas Telah Ada Mohon Cek Ulang');
        }

        Kelas::create([
            'jenis_kelas'=>$request->jenis_kelas,
        ]);

        return back()->with('success', 'Berhasil Menambahkan Kelas Baru');
    }


    public function update(Request $request, $id)
    {
        Kelas::find($id)->update([
            'jenis_kelas'=>$request->jenis_kelas
        ]);

        return back()->with('success', 'Berhasil Perbaharui Kelas');
    }

    
    public function destroy($id)
    {
        Kelas::find($id)->delete();

        return back()->with('success', 'Berhasil Menghapus Kelas');
    }
}

app/Http/Controllers/Petugas/LaporanPetugasController.php
<?php

namespace App\Http\Controllers\petugas;

use App\Http\Controllers\Controller;
use App\Models\Riwayat;
use Illuminate\Http\Request;

use PDF;

class LaporanPetugasController extends Controller
{
    public function index()
    {
        $riwayat = Riwayat::join('siswa', 'siswa.id_siswa', '=', 'riwayat_pinjam.id_siswa')
            ->join('kelas', 'kelas.id_kelas', '=', 'siswa.kelas')
            ->join('buku', 'buku.id_buku', '=', 'riwayat_pinjam.id_buku')
            ->select('riwayat_pinjam.*', 'buku.nama_buku', 'buku.kode_buku', 'buku.foto_buku', 'siswa.nis', 'siswa.nama_siswa', 'kelas.jenis_kelas')
            ->latest()
            ->get();

        return view('petugas.laporan.laporan', compact(['riwayat']));
    }

    public function cetak_pdf()
    {
        $riwayat = Riwayat::join('siswa', 'siswa.id_siswa', '=', 'riwayat_pinjam.id_siswa')
            ->join('kelas', 'kelas.id_kelas', '=', 'siswa.kelas')
            ->join('buku', 'buku.id_buku', '=', 'riwayat_pinjam.id_buku')
            ->select('riwayat_pinjam.*', 'buku.nama_buku', 'buku.kode_buku', 'buku.foto_buku', 'siswa.nis', 'siswa.nama_siswa', 'kelas.jenis_kelas')
            ->latest()
            ->get();

        $pdf = PDF::loadview('petugas.laporan.print_laporan_all', ['riwayat' => $riwayat]);

        return $pdf->stream();
    }

    public function cari_laporan(Request $request)
    {
        $data = explode(' - ', $request->daterange);

        $startDate = date('Y-m-d', strtotime($data[0]));
        $endDate = date('Y-m-d', strtotime($data[1]));

        $riwayat = Riwayat::join('siswa', 'siswa.id_siswa', '=', 'riwayat_pinjam.id_siswa')
            ->join('kelas', 'kelas.id_kelas', '=', 'siswa.kelas')
            ->join('buku', 'buku.id_buku', '=', 'riwayat_pinjam.id_buku')
            ->select('riwayat_pinjam.*', 'buku.nama_buku', 'buku.kode_buku', 'buku.foto_buku', 'siswa.nis', 'siswa.nama_siswa', 'kelas.jenis_kelas')
            ->whereBetween('riwayat_pinjam.tanggal_kembali', [$startDate, $endDate])
            ->get();

        $pdf = PDF::loadview('petugas.laporan.print_laporan_all', ['riwayat' => $riwayat]);
        return $pdf->stream();
    }
}

app/Http/Controllers/Petugas/PeminjamanPetugasController.php
<?php

namespace App\Http\Controllers\petugas;

use App\Http\Controllers\Controller;
use App\Models\Buku;
use App\Models\Pinjam;
use App\Models\Riwayat;
use App\Models\Siswa;
use Illuminate\Http\Request;

class PeminjamanPetugasController extends Controller
{
    public function index()
    {
        return view('petugas.peminjaman.peminjaman');
    }

    public function cek(Request $request)
    {
        $request->validate([
            'barcode'=>'required'
        ]);

        $barcode = $request->barcode;

        $buku = Buku::where('stok_buku','>',0)->orderBy('nama_buku', 'ASC')->get();

        $siswa = Siswa::join('kelas','kelas.id_kelas','=','siswa.kelas')
        ->select('siswa.*', 'kelas.jenis_kelas')
        ->where('siswa.barcode', $barcode)
        ->get();

        if($siswa->count() < 1)
        {
            return back()->with('fail','Mohon Maaf Data Siswa Tidak Di Temukan');
        }


        return view('petugas.peminjaman.peminjaman_cek', compact(['siswa','buku']));
    }


    public function pinjam(Request $request)
    {
        $siswa = Pinjam::where('id_siswa',$request->siswa)->get();
        $count =$siswa->count();

        if ($count > 0) {
            return back()->with('fail','Maaf Siswa Masih Memiliki Pinjaman Buku');
        }

        $request->validate([
            'buku1'=>'required'
        ]);

        $id_buku1 = $request->buku1;

        $tanggal = date('Y-m-d', strtotime("+7 day", strtotime(date("Y-m-d"))));

        Pinjam::create([
            'id_siswa'=>$request->siswa,
            'id_buku'=>$request->buku1,
            'tanggal_kembali'=>$tanggal

        ]);

        Buku::find($id_buku1)->decrement('stok_buku');

        Riwayat::create([
            'id_siswa'=>$request->siswa,
            'id_buku'=>$request->buku1,
            'tanggal_kembali'=>$tanggal,
            'status'=>'pinjam'
        ]);

        if (!empty($request->buku2)) {
            Pinjam::create([
                'id_siswa'=>$request->siswa,
                'id_buku'=>$request->buku2,
                'tanggal_kembali'=>$tanggal
            ]);

            $id_buku2 = $request->buku2;

            Buku::find($id_buku2)->decrement('stok_buku');

            Riwayat::create([
                'id_siswa'=>$request->siswa,
                'id_buku'=>$request->buku2,
                'tanggal_kembali'=>$tanggal,
                'status'=>'pinjam'
            ]);
        }
        if (!empty($request->buku3)) {
            Pinjam::create([
                'id_siswa'=>$request->siswa,
                'id_buku'=>$request->buku3,
                'tanggal_kembali'=>$tanggal
            ]);

            $id_buku3 = $request->buku3;

            Buku::find($id_buku3)->decrement('stok_buku');

            Riwayat::create([
                'id_siswa'=>$request->siswa,
                'id_buku'=>$request->buku3,
                'tanggal_kembali'=>$tanggal,
                'status'=>'pinjam'
            ]);
        }

        return to_route('peminjaman.index')->with('success', 'Berhasil Melakukan Peminjaman Buku');
    }
}

app/Http/Controllers/Petugas/RakPetugasController.php
<?php

namespace App\Http\Controllers\petugas;

use App\Http\Controllers\Controller;
use App\Models\Rak;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Validator;

class RakPetugasController extends Controller
{
    public function index()
    {
        $rak = Rak::orderBy('jenis_rak','ASC')->paginate(8);
        return view('petugas.rak.rak', compact(['rak']));
    }

    public function store(Request $request)
    {
        $validator = Validator::make($request->all(), [
            'jenis_rak'=> 'unique:rak,jenis_rak'
        ]);

        if ($validator->fails()) {
            return back()->with('fail', 'Rak Buku Telah Ada Mohon Cek Ulang');
        }

        rak::create([
            'jenis_rak'=>$request->jenis_rak,
        ]);

        return back()->with('success', 'Berhasil Menambahkan Rak Buku Baru');
    }


  
    public function update(Request $request, $id)
    {
        Rak::find($id)->update([
            'jenis_rak'=>$request->jenis_rak
        ]);

        return back()->with('success', 'Berhasil Perbaharui Rak Buku');
    }

    public function destroy($id)
    {
        Rak::find($id)->delete();

        return back()->with('success', 'Berhasil Menghapus Rak Buku');
    }
}

resources/views/petugas/theme/master.blade.php
<!DOCTYPE html>
<!-- yang mengerjakan Sem Wanadri -->
<html lang="en">

<head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no" />
    <title>SI - Perpustakaan</title>
    <meta name="description" content="A responsive bootstrap 4 admin dashboard template by hencework" />

    <!-- Favicon -->
    <link rel="shortcut icon" href="favicon.ico">
    <link rel="icon" href="https://sanbercode.com/logo-white.png" type="image/x-icon">

    @yield('css')

    <!-- Toggles CSS -->
    <link href="/theme/vendors/jquery-toggles/css/toggles.css" rel="stylesheet" type="text/css">
    <link href="/theme/vendors/jquery-toggles/css/themes/toggles-light.css" rel="stylesheet" type="text/css">

    <!-- Custom CSS -->
    <link href="/theme/dist/css/style.css" rel="stylesheet" type="text/css">

    <style>
        @media print {
            .noPrint {
                display: none;
            }
        }
    </style>
</head>

<body>


    <!-- HK Wrapper -->
    <div class="hk-wrapper hk-vertical-nav">

        <!-- Top Navbar -->

        @include('petugas.theme.topbar')

        {{-- <form role="search" class="navbar-search">
            <div class="position-relative">
                <a href="javascript:void(0);" class="navbar-search-icon"><span class="feather-icon"><i data-feather="search"></i></span></a>
                <input type="text" name="example-input1-group2" class="form-control" placeholder="Type here to Search">
                <a id="navbar_search_close" class="navbar-search-close" href="#"><span class="feather-icon"><i data-feather="x"></i></span></a>
            </div>
        </form> --}}
        <!-- /Top Navbar -->

        <!-- Vertical Nav -->
        @include('petugas.theme.navbar')
        <div id="hk_nav_backdrop" class="hk-nav-backdrop"></div>
        <!-- /Vertical Nav -->

        <!-- Setting Panel -->
        <div class="hk-settings-panel">
            <div class="nicescroll-bar position-relative">
                <div class="settings-panel-wrap">
                    <div class="settings-panel-head">
                        <img class="brand-img d-inline-block align-top" src="dist/img/logo-light.png" alt="brand" />
                        <a href="javascript:void(0);" id="settings_panel_close" class="settings-panel-close"><span
                                class="feather-icon"><i data-feather="x"></i></span></a>
                    </div>

                    <hr>
                    <h6 class="mb-5">Navigation</h6>
                    <p class="font-14">Menu comes in two modes: dark & light</p>
                    <div class="button-list hk-nav-select mb-10">
                        <button type="button" id="nav_light_select"
                            class="btn btn-outline-success btn-sm btn-wth-icon icon-wthot-bg"><span
                                class="icon-label"><i class="fa fa-sun-o"></i> </span><span class="btn-text">Light
                                Mode</span></button>
                        <button type="button" id="nav_dark_select"
                            class="btn btn-outline-light btn-sm btn-wth-icon icon-wthot-bg"><span class="icon-label"><i
                                    class="fa fa-moon-o"></i> </span><span class="btn-text">Dark Mode</span></button>
                    </div>
                    <hr>
                    <h6 class="mb-5">Top Nav</h6>
                    <p class="font-14">Choose your liked color mode</p>
                    <div class="button-list hk-navbar-select mb-10">
                        <button type="button" id="navtop_light_select"
                            class="btn btn-outline-light btn-sm btn-wth-icon icon-wthot-bg"><span class="icon-label"><i
                                    class="fa fa-sun-o"></i> </span><span class="btn-text">Light Mode</span></button>
                        <button type="button" id="navtop_dark_select"
                            class="btn btn-outline-success btn-sm btn-wth-icon icon-wthot-bg"><span
                                class="icon-label"><i class="fa fa-moon-o"></i> </span><span class="btn-text">Dark
                                Mode</span></button>
                    </div>
                    <hr>
                    <div class="d-flex justify-content-between align-items-center">
                        <h6>Scrollable Header</h6>
                        <div class="toggle toggle-sm toggle-simple toggle-light toggle-bg-success scroll-nav-switch">
                        </div>
                    </div>
                    <button id="reset_settings" class="btn btn-success btn-block btn-reset mt-30">Reset</button>
                </div>
            </div>
            <img class="d-none" src="dist/img/logo-light.png" alt="brand" />
            <img class="d-none" src="dist/img/logo-dark.png" alt="brand" />
        </div>
        <!-- /Setting Panel -->

        <!-- Main Content -->
        <div class="hk-pg-wrapper">

            @yield('content')

            <!-- Footer -->
            <div class="hk-footer-wrap container-fluid px-xxl-65 px-xl-20 noPrint">
                <footer class="footer">
                    <div class="row">
                        <div class="col-md-6 col-sm-12">
                            <p>Perpustakaan<a href="#" class="text-dark" target="_blank">Dari Kelompk 10 </a> ©
                                2024 | Repost by Kelompok 10

                            </p>
                        </div>
                    </div>
                </footer>
            </div>
            <!-- /Footer -->
        </div>
        <!-- /Main Content -->

    </div>
    <!-- /HK Wrapper -->

    <!-- jQuery -->
    <script src="/theme/vendors/jquery/dist/jquery.min.js"></script>

    <!-- Bootstrap Core JavaScript -->
    <script src="/theme/vendors/popper.js/dist/umd/popper.min.js"></script>
    <script src="/theme/vendors/bootstrap/dist/js/bootstrap.min.js"></script>

    <!-- Slimscroll JavaScript -->
    <script src="/theme/dist/js/jquery.slimscroll.js"></script>

    @yield('js')

    <!-- Fancy Dropdown JS -->
    <script src="/theme/dist/js/dropdown-bootstrap-extended.js"></script>

    <!-- Toggles JavaScript -->
    <script src="/theme/vendors/jquery-toggles/toggles.min.js"></script>
    <script src="/theme/dist/js/toggle-data.js"></script>

    <!-- FeatherIcons JavaScript -->
    <script src="/theme/dist/js/feather.min.js"></script>

    <!-- Init JavaScript -->
    <script src="/theme/dist/js/init.js"></script>

</body>

</html>

resources/views/petugas/theme/navbar.blade.php
<nav class="hk-nav hk-nav-light">
    <a href="javascript:void(0);" id="hk_nav_close" class="hk-nav-close"><span class="feather-icon"><i
                data-feather="x"></i></span></a>
    <div class="nicescroll-bar">
        <div class="navbar-nav-wrap">
            <div class="nav-header">
                <span>Data Siswa</span>
                <span>UI</span>
            </div>
            <ul class="navbar-nav flex-column">
                <li class="nav-item {{ request()->is('petugas/siswa*') ? 'active' : '' }}">
                    <a class="nav-link" href="{{ route('siswa.index') }}">
                        <i class="material-icons">school</i>
                        <span class="nav-link-text">Siswa</span>
                    </a>
                </li>
                <li class="nav-item {{ request()->is('petugas/kelas*') ? 'active' : '' }}">
                    <a class="nav-link" href="{{ route('kelas.index') }}">
                        <i class="material-icons">home</i>
                        <span class="nav-link-text"> Kelas</span>
                    </a>
                </li>
            </ul>
            <hr class="nav-separator">
            <div class="nav-header">
                <span>Buku</span>
                <span>UI</span>
            </div>
            <ul class="navbar-nav flex-column">
                <li class="nav-item {{ request()->is('petugas/buku*') ? 'active' : '' }}">
                    <a class="nav-link" href="{{ route('buku.index') }}">
                        <i class="material-icons">menu_book</i>
                        <span class="nav-link-text">Buku</span>
                    </a>
                </li>
                <li class="nav-item {{ request()->is('petugas/rak*') ? 'active' : '' }}">
                    <a class="nav-link" href="{{ route('rak.index') }}">
                        <i class="material-icons">shelves</i>
                        <span class="nav-link-text">Rak Buku</span>
                    </a>
                </li>
            </ul>
            <hr class="nav-separator">
            <div class="nav-header">
                <span>Petugas</span>
                <span>UI</span>
            </div>
            <ul class="navbar-nav flex-column">
                <li class="nav-item {{ request()->is('petugas/petugas*') ? 'active' : '' }}">
                    <a class="nav-link" href="{{ route('petugas.index') }}">
                        <i class="material-icons">groups</i>
                        <span class="nav-link-text">Petugas</span>
                    </a>
                </li>
            </ul>
            <hr class="nav-separator">
            <div class="nav-header">
                <span>Pengaturan</span>
                <span>UI</span>
            </div>
            <ul class="navbar-nav flex-column">
                <li class="nav-item {{ request()->is('petugas/denda*') ? 'active' : '' }}">
                    <a class="nav-link" href="{{ route('denda.index') }}">
                        <i class="material-icons">monetization_on</i>
                        <span class="nav-link-text">Denda</span>
                    </a>
                </li>
            </ul>
        </div>
    </div>
</nav>