routes/web.php
<?php

use App\Http\Controllers\DashboardController;
use App\Http\Controllers\HomeController;
use App\Http\Controllers\petugas\BukuPetugasController;
use App\Http\Controllers\Petugas\DashboardPetugasController;
use App\Http\Controllers\Petugas\DendaPetugasController;
use App\Http\Controllers\petugas\KelasPetugasController;
use App\Http\Controllers\petugas\LaporanPetugasController;
use App\Http\Controllers\petugas\PeminjamanPetugasController;
use App\Http\Controllers\petugas\PengambalianPetugasController;
use App\Http\Controllers\Petugas\PetugasController;
use App\Http\Controllers\petugas\ProfilPetugasController;
use App\Http\Controllers\petugas\RakPetugasController;
use App\Http\Controllers\Petugas\SiswaPetugasController;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

// Route::get('/', function () {
//     return view('welcome');
// });

Route::get('/', [DashboardController::class, 'index'])->name('home.index');
Route::get('/buku', [DashboardController::class, 'buku'])->name('home.buku');
Route::get('/buku/cari', [DashboardController::class, 'cari'])->name('home.cari');

Auth::routes();

Route::get('/home', [HomeController::class, 'index'])->name('home');

Route::middleware(['auth', 'user-access:Petugas'])->group(function () {
    Route::get('/petugas/dashboard', [DashboardPetugasController::class, 'index'])->name('petugas.dashboard');

    Route::resource('/petugas/siswa', SiswaPetugasController::class);

    Route::resource('/petugas/kelas', KelasPetugasController::class);

    Route::resource('/petugas/rak', RakPetugasController::class);

    Route::resource('/petugas/buku', BukuPetugasController::class);

    Route::resource('/petugas/petugas', PetugasController::class);

    Route::get('/petugas/peminjaman', [PeminjamanPetugasController::class, 'index'])->name('peminjaman.index');
    Route::get('/petugas/peminjaman/scan', [PeminjamanPetugasController::class, 'cek'])->name('peminjaman.scan');
    Route::post('/petugas/peminjaman/pinjam', [PeminjamanPetugasController::class, 'pinjam'])->name('peminjaman.store');

    Route::get('/petugas/pengembalian', [PengambalianPetugasController::class, 'index'])->name('pengembalian.index');
    Route::get('/petugas/pengembalian/scan', [PengambalianPetugasController::class, 'scan'])->name('pengembalian.scan');
    Route::post('/petugas/pengembalian/proses', [PengambalianPetugasController::class, 'proses'])->name('pengembalian.proses');

    Route::get('/petugas/profile', [ProfilPetugasController::class, 'index'])->name('profile.index');
    Route::put('/petugas/profile/edit-profile/{profile}', [ProfilPetugasController::class, 'data'])->name('profile.profile');
    Route::put('/petugas/profile/edit-password/{profile}', [ProfilPetugasController::class, 'password'])->name('profile.password');

    Route::get('/petugas/profile/foto', [ProfilPetugasController::class, 'foto'])->name('profile.foto');
    Route::put('/petugas/profile/foto-update/{profile}', [ProfilPetugasController::class, 'foto_update'])->name('profile.foto_update');

    Route::get('/petugas/laporan', [LaporanPetugasController::class, 'index'])->name('laporan.index');
    Route::get('/petugas/laporan/cetak', [LaporanPetugasController::class, 'cetak_pdf'])->name('laporan.cetak_pdf');
    Route::post('/petugas/laporan/cari', [LaporanPetugasController::class, 'cari_laporan'])->name('laporan.cari_laporan');

    Route::resource('/petugas/denda', DendaPetugasController::class);

});

app/Models/Kelas.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Kelas extends Model
{
    use HasFactory;

    protected $table = 'kelas';
    protected $primaryKey = 'id_kelas';
    protected $fillable = [
        'jenis_kelas'
    ];
}

app/Http/Controllers/Petugas/BukuPetugasController.php
<?php

namespace App\Http\Controllers\petugas;

use App\Http\Controllers\Controller;
use App\Models\Buku;
use App\Models\Rak;
use Illuminate\Http\Request;

class BukuPetugasController extends Controller
{
    public function index()
    {
        $buku = Buku::join('rak', 'rak.id_rak', '=', 'buku.rak')
            ->select('buku.*', 'rak.jenis_rak')
            ->orderBy('buku.nama_buku', 'ASC')
            ->get();

        return Response(view('petugas.buku.buku', compact(['buku'])));
    }

    public function create()
    {
        $rak = Rak::orderBy('jenis_rak', 'ASC')->get();
        return view('petugas.buku.buku_store', compact(['rak']));
    }

    public function store(Request $request)
    {
        $request->validate([
            'kode_buku' => 'required|unique:buku,kode_buku',
            'judul_buku' => 'required|unique:buku,nama_buku',
            'penerbit' => 'required',
            'rak' => 'required',
            'stok' => 'required',
            'foto' => 'required'
        ]);

        if ($request->hasFile('foto')) {
            $foto_profile = $request->file('foto')->getClientOriginalName();
            $request->foto->move(public_path('foto_buku'), $foto_profile);
        }

        Buku::create([
            'kode_buku' => $request->kode_buku,
            'nama_buku' => $request->judul_buku,
            'penerbit' => $request->penerbit,
            'rak' => $request->rak,
            'stok_buku' => $request->stok,
            'foto_buku' => $foto_profile,
        ]);

        return to_route('buku.index')->with('success', 'Berhasil Menambahkan Buku Baru');
    }

    public function show($id)
    {
        //
    }

    public function edit($id)
    {
        $buku = Buku::find($id);
        $rak = Rak::orderBy('jenis_rak', 'ASC')->get();

        return view('petugas.buku.buku_edit', compact(['buku', 'rak']));
    }

    public function update(Request $request, $id)
    {
        $request->validate([
            'kode_buku' => 'required',
            'judul_buku' => 'required',
            'penerbit' => 'required',
            'rak' => 'required',
            'stok' => 'required',
        ]);

        if ($request->foto == NULL) {
            Buku::find($id)->update([
                'kode_buku' => $request->kode_buku,
                'nama_buku' => $request->judul_buku,
                'penerbit' => $request->penerbit,
                'rak' => $request->rak,
                'stok_buku' => $request->stok,
            ]);

            return to_route('buku.index')->with('success', 'Berhasil Memperbaharui Data Buku');
        }

        if ($request->hasFile('foto')) {
            $foto_profile = $request->file('foto')->getClientOriginalName();
            $request->foto->move(public_path('foto_buku'), $foto_profile);
        }

        Buku::find($id)->update([
            'kode_buku' => $request->kode_buku,
            'nama_buku' => $request->judul_buku,
            'penerbit' => $request->penerbit,
            'rak' => $request->rak,
            'stok_buku' => $request->stok,
            'foto_buku' => $foto_profile,
        ]);

        return to_route('buku.index')->with('success', 'Berhasil Memperbaharui Data Buku');
    }

    public function destroy($id)
    {
        Buku::find($id)->delete();

        return back()->with('success', 'Berhasil Menghapus Buku');
    }
}

app/Http/Controllers/Petugas/DashboardPetugasController.php
<?php

namespace App\Http\Controllers\Petugas;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\DB;

class DashboardPetugasController extends Controller
{
    public function index()
    {
        $siswa = DB::table('siswa')->get();
        $buku = DB::table('buku')->get();
        $pinjam = DB::table('riwayat_pinjam')->where('status', 'pinjam')->get();
        $kembali = DB::table('riwayat_pinjam')->where('status', 'selesai')->get();
        $aktivity = DB::table('riwayat_pinjam')
            ->join('siswa', 'siswa.id_siswa', '=', 'riwayat_pinjam.id_siswa')
            ->join('buku', 'buku.id_buku', '=', 'riwayat_pinjam.id_buku')
            ->select('riwayat_pinjam.*', 'siswa.nama_siswa', 'siswa.foto', 'buku.nama_buku')
            ->latest()
            ->limit(5)
            ->get();

        return view('petugas.dashboard.dashboard', compact('siswa', 'buku', 'pinjam', 'kembali', 'aktivity'));
    }
}

app/Http/Controllers/Petugas/DendaPetugasController.php
<?php

namespace App\Http\Controllers\Petugas;

use App\Http\Controllers\Controller;
use App\Models\Denda;
use Illuminate\Http\Request;

class DendaPetugasController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $denda = Denda::get();
        return view('petugas.denda.denda', compact(['denda']));
    }

    public function store(Request $request)
    {
        Denda::create([
            'nominal_denda' => $request->nominal_denda,
        ]);

        return back()->with('success', 'Berhasil Menambahkan Denda Peminjaman');
    }
    public function update(Request $request, $id)
    {
        Denda::find($id)->update([
            'nominal_denda' => $request->nominal_denda,
        ]);

        return back()->with('success', 'Berhasil Memperbaharui Denda Peminjaman');
    }

    public function destroy($id)
    {
        Denda::find($id)->delete();

        return back()->with('success', 'Berhasil Menghapus Denda Peminjaman');
    }
}

app/Http/Controllers/Petugas/KelasPetugasController.php
<?php

namespace App\Http\Controllers\petugas;

use App\Http\Controllers\Controller;
use App\Models\Kelas;
use Illuminate\Support\Facades\Validator;
use Illuminate\Http\Request;

class KelasPetugasController extends Controller
{
   
    public function index()
    {
        $kelas = Kelas::orderBy('jenis_kelas', 'ASC')->paginate(8);
        return view('petugas.kelas.kelas', compact(['kelas']));
    }


    public function store(Request $request)
    {
        $validator = Validator::make($request->all(), [
            'jenis_kelas'=> 'unique:kelas,jenis_kelas'
        ]);

        if ($validator->fails()) {
            return back()->with('fail', 'Kelas Telah Ada Mohon Cek Ulang');
        }

        Kelas::create([
            'jenis_kelas'=>$request->jenis_kelas,
        ]);

        return back()->with('success', 'Berhasil Menambahkan Kelas Baru');
    }


    public function update(Request $request, $id)
    {
        Kelas::find($id)->update([
            'jenis_kelas'=>$request->jenis_kelas
        ]);

        return back()->with('success', 'Berhasil Perbaharui Kelas');
    }

    
    public function destroy($id)
    {
        Kelas::find($id)->delete();

        return back()->with('success', 'Berhasil Menghapus Kelas');
    }
}

app/Http/Controllers/Petugas/LaporanPetugasController.php
<?php

namespace App\Http\Controllers\petugas;

use App\Http\Controllers\Controller;
use App\Models\Riwayat;
use Illuminate\Http\Request;

use PDF;

class LaporanPetugasController extends Controller
{
    public function index()
    {
        $riwayat = Riwayat::join('siswa', 'siswa.id_siswa', '=', 'riwayat_pinjam.id_siswa')
            ->join('kelas', 'kelas.id_kelas', '=', 'siswa.kelas')
            ->join('buku', 'buku.id_buku', '=', 'riwayat_pinjam.id_buku')
            ->select('riwayat_pinjam.*', 'buku.nama_buku', 'buku.kode_buku', 'buku.foto_buku', 'siswa.nis', 'siswa.nama_siswa', 'kelas.jenis_kelas')
            ->latest()
            ->get();

        return view('petugas.laporan.laporan', compact(['riwayat']));
    }

    public function cetak_pdf()
    {
        $riwayat = Riwayat::join('siswa', 'siswa.id_siswa', '=', 'riwayat_pinjam.id_siswa')
            ->join('kelas', 'kelas.id_kelas', '=', 'siswa.kelas')
            ->join('buku', 'buku.id_buku', '=', 'riwayat_pinjam.id_buku')
            ->select('riwayat_pinjam.*', 'buku.nama_buku', 'buku.kode_buku', 'buku.foto_buku', 'siswa.nis', 'siswa.nama_siswa', 'kelas.jenis_kelas')
            ->latest()
            ->get();

        $pdf = PDF::loadview('petugas.laporan.print_laporan_all', ['riwayat' => $riwayat]);

        return $pdf->stream();
    }

    public function cari_laporan(Request $request)
    {
        $data = explode(' - ', $request->daterange);

        $startDate = date('Y-m-d', strtotime($data[0]));
        $endDate = date('Y-m-d', strtotime($data[1]));

        $riwayat = Riwayat::join('siswa', 'siswa.id_siswa', '=', 'riwayat_pinjam.id_siswa')
            ->join('kelas', 'kelas.id_kelas', '=', 'siswa.kelas')
            ->join('buku', 'buku.id_buku', '=', 'riwayat_pinjam.id_buku')
            ->select('riwayat_pinjam.*', 'buku.nama_buku', 'buku.kode_buku', 'buku.foto_buku', 'siswa.nis', 'siswa.nama_siswa', 'kelas.jenis_kelas')
            ->whereBetween('riwayat_pinjam.tanggal_kembali', [$startDate, $endDate])
            ->get();

        $pdf = PDF::loadview('petugas.laporan.print_laporan_all', ['riwayat' => $riwayat]);
        return $pdf->stream();
    }
}

app/Http/Controllers/Petugas/PeminjamanPetugasController.php
<?php

namespace App\Http\Controllers\petugas;

use App\Http\Controllers\Controller;
use App\Models\Buku;
use App\Models\Pinjam;
use App\Models\Riwayat;
use App\Models\Siswa;
use Illuminate\Http\Request;

class PeminjamanPetugasController extends Controller
{
    public function index()
    {
        return view('petugas.peminjaman.peminjaman');
    }

    public function cek(Request $request)
    {
        $request->validate([
            'barcode'=>'required'
        ]);

        $barcode = $request->barcode;

        $buku = Buku::where('stok_buku','>',0)->orderBy('nama_buku', 'ASC')->get();

        $siswa = Siswa::join('kelas','kelas.id_kelas','=','siswa.kelas')
        ->select('siswa.*', 'kelas.jenis_kelas')
        ->where('siswa.barcode', $barcode)
        ->get();

        if($siswa->count() < 1)
        {
            return back()->with('fail','Mohon Maaf Data Siswa Tidak Di Temukan');
        }


        return view('petugas.peminjaman.peminjaman_cek', compact(['siswa','buku']));
    }


    public function pinjam(Request $request)
    {
        $siswa = Pinjam::where('id_siswa',$request->siswa)->get();
        $count =$siswa->count();

        if ($count > 0) {
            return back()->with('fail','Maaf Siswa Masih Memiliki Pinjaman Buku');
        }

        $request->validate([
            'buku1'=>'required'
        ]);

        $id_buku1 = $request->buku1;

        $tanggal = date('Y-m-d', strtotime("+7 day", strtotime(date("Y-m-d"))));

        Pinjam::create([
            'id_siswa'=>$request->siswa,
            'id_buku'=>$request->buku1,
            'tanggal_kembali'=>$tanggal

        ]);

        Buku::find($id_buku1)->decrement('stok_buku');

        Riwayat::create([
            'id_siswa'=>$request->siswa,
            'id_buku'=>$request->buku1,
            'tanggal_kembali'=>$tanggal,
            'status'=>'pinjam'
        ]);

        if (!empty($request->buku2)) {
            Pinjam::create([
                'id_siswa'=>$request->siswa,
                'id_buku'=>$request->buku2,
                'tanggal_kembali'=>$tanggal
            ]);

            $id_buku2 = $request->buku2;

            Buku::find($id_buku2)->decrement('stok_buku');

            Riwayat::create([
                'id_siswa'=>$request->siswa,
                'id_buku'=>$request->buku2,
                'tanggal_kembali'=>$tanggal,
                'status'=>'pinjam'
            ]);
        }
        if (!empty($request->buku3)) {
            Pinjam::create([
                'id_siswa'=>$request->siswa,
                'id_buku'=>$request->buku3,
                'tanggal_kembali'=>$tanggal
            ]);

            $id_buku3 = $request->buku3;

            Buku::find($id_buku3)->decrement('stok_buku');

            Riwayat::create([
                'id_siswa'=>$request->siswa,
                'id_buku'=>$request->buku3,
                'tanggal_kembali'=>$tanggal,
                'status'=>'pinjam'
            ]);
        }

        return to_route('peminjaman.index')->with('success', 'Berhasil Melakukan Peminjaman Buku');
    }
}

app/Http/Controllers/Petugas/RakPetugasController.php
<?php

namespace App\Http\Controllers\petugas;

use App\Http\Controllers\Controller;
use App\Models\Rak;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Validator;

class RakPetugasController extends Controller
{
    public function index()
    {
        $rak = Rak::orderBy('jenis_rak','ASC')->paginate(8);
        return view('petugas.rak.rak', compact(['rak']));
    }

    public function store(Request $request)
    {
        $validator = Validator::make($request->all(), [
            'jenis_rak'=> 'unique:rak,jenis_rak'
        ]);

        if ($validator->fails()) {
            return back()->with('fail', 'Rak Buku Telah Ada Mohon Cek Ulang');
        }

        rak::create([
            'jenis_rak'=>$request->jenis_rak,
        ]);

        return back()->with('success', 'Berhasil Menambahkan Rak Buku Baru');
    }


  
    public function update(Request $request, $id)
    {
        Rak::find($id)->update([
            'jenis_rak'=>$request->jenis_rak
        ]);

        return back()->with('success', 'Berhasil Perbaharui Rak Buku');
    }

    public function destroy($id)
    {
        Rak::find($id)->delete();

        return back()->with('success', 'Berhasil Menghapus Rak Buku');
    }
}

resources/views/petugas/kelas/kelas.blade.php
@extends('petugas.theme.master')

@section('content')
    <div class="container-fluid px-xxl-65 px-xl-20 mt-20">
        <!-- Title -->
        <div class="hk-pg-header">
            <h4 class="hk-pg-title"><span class="pg-title-icon">
                    <i class="material-icons">home</i></span>Data Kelas
            </h4>
        </div>


        @if (session('success'))
            <div class="alert alert-success alert-wth-icon fade show" role="alert">
                <span class="alert-icon-wrap"><i class="zmdi zmdi-check-circle"></i></span>
                {{ session('success') }}
            </div>
        @elseif (session('fail'))
            <div class="alert alert-danger alert-wth-icon fade show" role="alert">
                <span class="alert-icon-wrap"><i class="zmdi zmdi-block"></i></span>
                {{ session('fail') }}
            </div>
        @endif
        <div class="row justify-content-md-center">
            <div class="col-xl-6">
                <section class="hk-sec-wrapper">
                    <p class="mb-40">
                        <button class="btn btn-success btn-wth-icon btn-sm" data-toggle="modal" data-target="#createkelas">
                            <span class="icon-label">
                                <span class="material-icons">
                                    control_point
                                </span>
                            </span>
                            <span class="btn-text">Tambah Kelas Baru</span>
                        </button>
                    <div class="modal fade" id="createkelas" tabindex="-1" role="dialog" aria-labelledby="createkelas"
                        aria-hidden="true">
                        <div class="modal-dialog modal-dialog-centered" role="document">
                            <div class="modal-content">
                                <div class="modal-header">
                                    <h5 class="modal-title">Form Tambah Kelas</h5>
                                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                        <span aria-hidden="true">&times;</span>
                                    </button>
                                </div>
                                <form action="{{ route('kelas.store') }}" method="post" enctype="multipart/form-data">
                                    @csrf
                                    @method('post')
                                    <div class="modal-body">
                                        <div class="form-group">
                                            <label for="validationCustom01">Nama Kelas</label>
                                            <input type="text" class="form-control" name="jenis_kelas"
                                                id="validationCustom01" placeholder="Kelas 3 A" required>
                                        </div>
                                    </div>
                                    <div class="modal-footer">
                                        <button type="button" class="btn btn-secondary" data-dismiss="modal">Tutup</button>
                                        <button class="btn btn-success" type="submit">Simpan
                                            Kelas</button>
                                    </div>
                                </form>
                            </div>
                        </div>
                    </div>
                    </p>
                    <div class="row">
                        <div class="col-sm">
                            <div class="table-wrap">
                                <div class="table-responsive">
                                    <table class="table table-sm mb-0">
                                        <thead>
                                            <tr>
                                                <th>Kelas</th>
                                                <th>Action</th>
                                            </tr>
                                        </thead>
                                        <tbody>
                                            @foreach ($kelas as $data)
                                                <tr>
                                                    <td>{{ Str::upper($data->jenis_kelas) }}</td>
                                                    <td>
                                                        <a href="" data-toggle="modal"
                                                            data-target="#updatekelas{{ $data->id_kelas }}" class="mr-25"
                                                            data-toggle="tooltip" data-original-title="Edit"> <i
                                                                class="icon-pencil"></i> </a>
                                                        <a href="{{ route('kelas.destroy', $data->id_kelas) }}" data-toggle="tooltip" data-original-title="Hapus"
                                                            onclick="event.preventDefault();
                                                            document.getElementById('kelas-delete-form-{{ $data->id_kelas }}').submit();">
                                                            <i class="icon-trash txt-danger" style="color: red"></i></a>
                                                            <form id="kelas-delete-form-{{ $data->id_kelas }}" action="{{ route('kelas.destroy', $data->id_kelas) }}" method="POST" class="d-none">
                                                                @csrf
                                                                @method('delete')
                                                            </form>
                                                    </td>
                                                    <div class="modal fade" id="updatekelas{{ $data->id_kelas }}" tabindex="-1" role="dialog"
                                                        aria-labelledby="updatekelas{{ $data->id_kelas }}" aria-hidden="true">
                                                        <div class="modal-dialog modal-dialog-centered" role="document">
                                                            <div class="modal-content">
                                                                <div class="modal-header">
                                                                    <h5 class="modal-title">Edit Kelas</h5>
                                                                    <button type="button" class="close"
                                                                        data-dismiss="modal" aria-label="Close">
                                                                        <span aria-hidden="true">&times;</span>
                                                                    </button>
                                                                </div>
                                                                <form action="{{ route('kelas.update', $data->id_kelas) }}" method="post"
                                                                    enctype="multipart/form-data">
                                                                    @csrf
                                                                    @method('put')
                                                                    <div class="modal-body">
                                                                        <div class="form-group">
                                                                            <label for="validationCustom01">Nama
                                                                                Kelas</label>
                                                                            <input type="text" class="form-control"
                                                                                name="jenis_kelas" id="validationCustom01"
                                                                                placeholder="Kelas 3 A" value="{{ $data->jenis_kelas }}" required>
                                                                        </div>
                                                                    </div>
                                                                    <div class="modal-footer">
                                                                        <button type="button" class="btn btn-secondary"
                                                                            data-dismiss="modal">Tutup</button>
                                                                        <button class="btn btn-success"
                                                                            type="submit">Perbaharui
                                                                            Kelas</button>
                                                                    </div>
                                                                </form>
                                                            </div>
                                                        </div>
                                                    </div>
                                                </tr>
                                            @endforeach
                                        </tbody>
                                    </table>
                                </div>
                            </div>
                            <div class="d-felx justify-content-center mt-2">
                                {{ $kelas->links('pagination::bootstrap-5') }}
                            </div>
                        </div>
                    </div>
                </section>
            </div>
        </div>
    </div>
@endsection

@section('js')
    <script>
        window.setTimeout(function() {
            $(".alert").fadeTo(700, 0).slideUp(500, function() {
                $(this).remove();
            });
        }, 2500);
    </script>
@endsection